channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
  - matplotlib
  - jupyterlab
  - python=3.11
  - scipy
  - torchaudio
  - torchvision
  - pytorch::pytorch
  - pytorch-cuda
  - pygame
  - stable-baselines3
  - gymnasium
  - sb3-contrib